RHBZ#1956387 tuned-adm: add --verbose option to verify command
redhat-performance/tuned pull request #346
Opened 2021-05-13 07:55 UTC by pjps

'tuned-adm verify' command validates system settings against the
active tuned(8) profiles. But it does not show detailed validation
results to the user. User is left to sift through the tuned(8) log
file to figure it out.

Adding '--verbose' option to the tuned-adm command addresses
this issue. It enables tuned(8) daemon to collect and return
detailed validation results back to the tuned-adm program.
tuned-adm displays these results on the console.

It enables users to confirm that active tuned(8) profile settings
are effective on the system.

Fixes: RHBZ#1956387

2021-05-19 08:54 UTC, yarda approved these changes
Thanks for contribution. The change LGTM. The only concern I currently have is the API change - verify_profile* methods now also returning string. I checked Cockpit Project (which is known consumer of the API) and it doesn't call these methods. Adding v2 D-Bus interface or new methods seems as unnecessary complication to me (taking into account that the 'verify' functionality is usually not much used by regular users). AFAIK we have never claimed the API to be stable so the change is probably OK.

It's bigger change, so also adding jzerdik to review it in case I missed anything. In the meantime I will run tier1 tests on the scratch build to be 100% sure there is no regression.

2021-05-20 08:55 UTC, CZerta commented on tuned/plugins/plugin_modules.py
> +				ret = True
Should this line be here? If something already failed and this will be last run through cycle, it would overwrite False result.

2021-05-20 08:55 UTC, CZerta commented on tuned/verifylog.py
> +		for i in range(len(log)):
I would rewrite these functions more pythonic/readable. Var i is used just for index, so it can be "for l in log" or smth.

2021-05-20 08:55 UTC, CZerta commented on tuned/verifylog.py
> +					for k in dev.keys():
Similar to above, why not use "for k, v in dev.items()"? Also similar in other functions down there.

2021-05-20 10:49 UTC, yarda requested changes
Dropping approval, because we agreed off channel on some design changes that will be compatible with the 3rd party plugins.

2021-05-24 11:45 UTC, closed without merging