Fix conditional order for setting net device param
redhat-performance/tuned pull request #360
Opened 2021-06-20 09:16 UTC by yanirq

The conditional for setting a net device parameter has
a faulty order where it can potentially try to first cast a string to int
in a wrong manner and only then check if the value is a specific integer value.

current order:
1. check if a net device has a combined channel containing 0
2. check if a net device has a combined channel containing 'n/a'

fixed order:
1. check if a net device has a combined channel containing 'n/a'
2. check if a net device has a combined channel containing 0

Signed-off-by: Yanir Quinn <yquinn@redhat.com>

2021-06-20 09:17 UTC, yanirq commented
/cc @yarda

2021-06-21 08:41 UTC, CZerta approved these changes
Seems ok, definitely reasonable

2021-06-21 22:54 UTC, yarda requested changes
Although unlikely it could still fail with traceback if there is different string returned than 'n/a'. Could you rewrite it to something more robust and more simple like e.g.:
```
if context == "channels" and str(dev_params[next(iter(d))]) in ["n/a", "0"]:
```

2021-06-22 07:28 UTC, yarda commented
@yanirq, could you please merge the commits to one and force push?

2021-06-22 08:04 UTC, yarda approved these changes
LGTM, thanks.

2021-06-22 08:11 UTC, merged