beakerlibtests: add new test
redhat-performance/tuned pull request #385
Opened 2021-10-06 10:01 UTC by RHEmployee

Add another test which seems suitable to upstream.

2021-10-13 08:32 UTC, yarda commented on tests/beakerlib/variables-support-in-profiles/runtest.sh
> +#   Copyright Red Hat
The same apply as in #384.

2021-10-13 15:47 UTC, yarda requested changes
Please fix the test not to fail on epel-8 and centos-stream.

2022-01-17 11:18 UTC, yarda commented
/packit build

2022-01-17 11:44 UTC, RHEmployee commented
Hello. Thank you for your support. Should be sovlved now.

2022-01-17 12:20 UTC, merged