Add missing entries in the OPTIONS section
redhat-performance/tuned pull request #456
Opened 2022-08-15 10:33 UTC by uniontech-lilinjie

Add missing options profile_info, auto_profile and profile mode in the OPTIONS section of the README.
Signed-off-by: lilinjie <lilinjie@uniontech.com>

2022-09-06 22:14 UTC, yarda commented
/packit build

2022-09-06 22:19 UTC, yarda requested changes
Thanks for the PR, I think some changes are needed for consistency.

2022-09-06 22:19 UTC, yarda commented on README
> +To verifies current profile against system settings, run:
I think this should spell either:
'To verify....' or 'Verifies...', but if there is ', run:', I think it should be 'To verify:'

2022-09-06 22:19 UTC, yarda commented on README
> +Enable automatic profile selection mode, switch to the recommended profile, run:
If there is ', run:' I think it should be 'To enable...', or drop the ', run'.

2022-09-06 22:19 UTC, yarda commented on README
> +Show current profile selection mode, run:
If there is ', run:' I think it should be 'To show...', or drop the ', run'.

2022-09-07 01:44 UTC, uniontech-lilinjie commented
&nbsp;hello, I revised it as you suggested (PR #456)

&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, Sep 7, 2022 06:20 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [redhat-performance/tuned] Add missing entries in the OPTIONS section (PR #456)

&nbsp;



 
@yarda requested changes on this pull request.
 
Thanks for the PR, I think some changes are needed for consistency.

 
In README:
 &gt; @@ -46,6 +46,18 @@ choice is used when the daemon is restarted (e.g. with the machine reboot).  To disable all tunings, run:  # tuned-adm off   +To show information/description of given profile or current profile if no profile is specified, run: +# tuned-adm profile_info + +To verifies current profile against system settings, run:  
I think this should spell either:
 'To verify....' or 'Verifies...', but if there is ', run:', I think it should be 'To verify:'
 
 
In README:
 &gt; @@ -46,6 +46,18 @@ choice is used when the daemon is restarted (e.g. with the machine reboot).  To disable all tunings, run:  # tuned-adm off   +To show information/description of given profile or current profile if no profile is specified, run: +# tuned-adm profile_info + +To verifies current profile against system settings, run: +# tuned-adm verify + +Enable automatic profile selection mode, switch to the recommended profile, run:  
If there is ', run:' I think it should be 'To enable...', or drop the ', run'.
 
 
In README:
 &gt; @@ -46,6 +46,18 @@ choice is used when the daemon is restarted (e.g. with the machine reboot).  To disable all tunings, run:  # tuned-adm off   +To show information/description of given profile or current profile if no profile is specified, run: +# tuned-adm profile_info + +To verifies current profile against system settings, run: +# tuned-adm verify + +Enable automatic profile selection mode, switch to the recommended profile, run: +# tuned-adm auto_profile + +Show current profile selection mode, run:  
If there is ', run:' I think it should be 'To show...', or drop the ', run'.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2022-10-02 23:12 UTC, merged