Adding pm_qos_resume_latency_us option for cpu plugin.
redhat-performance/tuned pull request #485
Opened 2022-12-05 12:22 UTC by CZerta

Resolves: rhbz#2118786

Signed-off-by: Jan Zerdik <jzerdik@redhat.com>

2022-12-05 12:56 UTC, CZerta commented
@joemario Should we disable dynamic tuning similarly as it is dissabled with `force_latency` option?

2022-12-06 18:09 UTC, joemario commented
Thank you Jaroslav for the info on dynamic tuning.  I was unaware of those details.

2023-02-08 11:22 UTC, yarda approved these changes

2023-02-08 11:24 UTC, yarda requested changes
Please fix the conflict.

2023-02-08 11:57 UTC, yarda approved these changes

2023-02-08 11:57 UTC, merged