plugin_scheduler: make perf support optional
redhat-performance/tuned pull request #716
Opened 2024-12-02 16:46 UTC by yarda

Requested in: https://src.fedoraproject.org/rpms/tuned/pull-request/8

2024-12-02 18:45 UTC, travier approved these changes
Thanks, LGTM

2025-01-14 12:04 UTC, zacikpa requested changes
Works well, checked the functionality with `python3-perf` uninstalled.

Just one nit, see my comment.

2025-01-14 12:04 UTC, zacikpa commented on tuned/plugins/plugin_scheduler.py
> +				log.warn("python-perf unavailable, disabling perf support, you can try to (re)install python(3)-perf package")
I believe `logging.warn` is deprecated in favor of `logging.warning`. We recently moved to using the latter. Also, it would be nice if the warning said that we are disabling runtime tuning.

2025-01-16 21:00 UTC, yarda commented on tuned/plugins/plugin_scheduler.py
> +				log.warn("python-perf unavailable, disabling perf support, you can try to (re)install python(3)-perf package")
It seems I was used to it for very long :). Fixed and updated the string.

2025-01-17 07:13 UTC, zacikpa approved these changes
Looks good now, thanks!

2025-01-18 18:54 UTC, merged